### PR TITLE
Add baseline search spaces for LAMB, SAM, Adafactor, and Shampoo

### PR DESCRIPTION
**Pull request by bilal2vec**
Adds baseline search spaces for LAMB, SAM, Adafactor, and Shampoo. Includes search spaces for tuning beta 1 and keeping beta 1 fixed.

### CODE REVIEW

**Comment by bilal2vec** [comment]
recheck

**Comment by bilal2vec** [comment]
recheck

**Comment by bilal2vec** [comment]
recheck

**Comment by bilal2vec** [comment]
recheck

**Review by znado — APPROVED** [review]

**Pull request merged**
