### PR TITLE
Update Dataset Setup

### PR DESCRIPTION
**Pull request by fsschneider**
I updated the dataset setup and corresponding readme in the following ways:

- Update the package version to `0.1.0` (from `0.0.1`) to match the git tag.
- Restructured the dataset setup readme.
- Fixed the bash command for OGBG to use `data_dir` instead of `data_dir/ogbg`.
- Standardized how subfolders for datasets are implemented.
- Add to the readme how the directory structure and number and sizes of the files should look like as a check. @priyakasimbeg could you double-check that they are the same in your setup?
- Highlight the need for `ffmpeg` and `pigz` in the readme.
- Move `pydub` to a LibriSpeech dependency.
- Fix `fastMRI` directory structure (see below).
- Add missing download and disk sizes in the documentation.

With the last point, there are still two open todos

- [x] Missing directory structures and file sizes/numbers for Criteo1TB, ImageNet (JAX), and LibriSpeech. I am still downloading the former. @priyakasimbeg could you provide those for us? Especially the ImageNet (JAX) as I am not sure I will use it anytime soon.
- [x] If I am not mistaken, then the output of the fastMRI dataset setup does not match what we require for the workload. Specifically, the setup produces:
```bash
fastmri
├── test
    ├── singlecoil_test
        ├── file1000022.h5
        ├── [...]
├── train
    ├── singlecoil_train
        ├── file1000001.h5
        ├── [...]
├── val
    ├── singlecoil_val
        ├── file1000000.h5
        ├── [...]
```
While I believe, our workload expects:
```bash
fastmri
├── knee_singlecoil_test
    ├── file1000022.h5
    ├── [...]
├── knee_singlecoil_train
    ├── file1000001.h5
    ├── [...]
├── knee_singlecoil_val
    ├── file1000000.h5
    ├── [...]
```

It is simply a once-more nested version with slightly different folder names. @priyakasimbeg can you verify that this is what is happening?

There are two ways to fix this, either change the dataset setup function (to match what the workload expects) or fix the workload (to what the setup produces). I have a slight preference for the former, what about you @priyakasimbeg? In both cases, I could fix this with this PR if you want.

### CODE REVIEW

**Comment by priyakasimbeg** [comment]
Hi Frank,
Thanks for getting these fixes in!

**Regarding FastMRI**; you're correct, it looks like the datasetup script adds one more layer and slightly different folder names. Yes, let's modify the data setup script in this PR so that it produces the following structure, like the workload expects: 
```
fastmri
├── knee_singlecoil_test
    ├── file1000022.h5
    ├── [...]
├── knee_singlecoil_train
    ├── file1000001.h5
    ├── [...]
├── knee_singlecoil_val
    ├── file1000000.h5
    ├── [...]
```

**Missing directory structures**

imagenet: 

```
$DATA_DIR
├──imagenet
│  ├── jax
│  │   ├── downloads
│  │   │   ├── extracted
│  │   │   └── manual_
│  │   ├── imagenet2012
│  │   │   └── 5.1.0
│  │   │       ├── dataset_info.json
│  │   │       ├── features.json
│  │   │       ├── imagenet2012-train.tfrecord-00000-of-01024
│  │   │       ├── imagenet2012-train.tfrecord-00001-of-01024
│  │   │       ├── imagenet2012-train.tfrecord-00002-of-01024
│  │   └── imagenet_v2
│  │       └── matched-frequency
│  │           └── 3.0.0
│  │               ├── dataset_info.json
│  │               ├── features.json
│  │               ├── imagenet_v2-test.tfrecord-00000-of-00016
│  │               ├── imagenet_v2-test.tfrecord-00001-of-00016
```
In total, $DATA_DIR/imagenet/jax should contain 1111 files (via `find -type f | wc -l`) for a total of 145 GB (via `du -sch imagenet/jax`).

criteo1tb

```
$DATA_DIR
├── criteo1tb
│  ├── day_0_00
│  ├── day_0_01
│  ├── day_0_02
│  ├── day_0_04
```
In total, $DATA_DIR/criteo1tb should contain 885 files (via `find -type f | wc -l`) for a total of 1.1TB (via `du -sch criteo1tb`).


librispeech
```
$DATA_DIR 
├──librispeech
│  ├── dev-clean
│  │   ├── 1272-128104-0000_audio.npy
│  │   ├── 1272-128104-0000_targets.npy
│  ├── dev-clean.csv
│  ├── dev-other
│  │   ├── 116-288045-0000_audio.npy
│  │   ├── 116-288045-0000_targets.npy
│  ├── dev-other.csv
│  ├── spm_model.vocab
│  ├── test-clean
│  │   ├── 1089-134686-0000_audio.npy  
│  │   ├── 1089-134686-0000_targets.npy
│  ├── test-clean.csv
│  ├── train-clean-100
│  │   ├── 103-1240-0000_audio.npy
│  │   ├── 103-1240-0000_targets.npy
│  ├── train-clean-100.csv
│  ├── train-clean-360
│  │   ├── 100-121669-0000_audio.npy
│  │   ├── 100-121669-0000_targets.npy
│  ├── train-clean-360.csv
│  │   ├── 985-126228-0050_audio.npy
│  │   └── 985-126228-0050_targets.npy
│  └── train-other-500.csv
```
In total, $DATA_DIR/criteo1tb should contain 543323 files (via `find -type f | wc -l`) for a total of 388GB (via `du -sch criteo1tb`).

**Comment by fsschneider** [comment]
@priyakasimbeg Just to double check:
For me, Criteo 1TB looks like this:
```bash
$DATA_DIR
├── criteo1tb
│  ├── day_0_000.csv
│  ├── day_0_001.csv
│  ├── day_0_002.csv
│  ├── day_0_003.csv
│  ├── [...]
```

while you reported (note the missing file `03` and the missing padded zero compared to my version)
```bash
$DATA_DIR
├── criteo1tb
│  ├── day_0_00
│  ├── day_0_01
│  ├── day_0_02
│  ├── day_0_04
```

I am pretty sure these are negligible differences as I get the same number of total files and file size.

**Comment by priyakasimbeg** [comment]
Hi Frank, thanks for finding that criteo data setup diff. We can ignore the diff with the missing file (I just happened to have cut it out of the markdown copy).  Regarding the file formats, this is an issue unfortunately. We use the filename format here in the input pipeline https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/criteo1tb/input_pipeline.py#L102-L103.  Let me look into this a little further. We can either change the input pipeline or change the data setup script. I prefer changing the data setup script since we have the input pipeline compatible format downloaded on all of the VMs already.

**Comment by priyakasimbeg** [comment]
I'm testing a modification to the criteo datasetup script in this PR https://github.com/mlcommons/algorithmic-efficiency/pull/604.

**Comment by fsschneider** [comment]
Thanks @priyakasimbeg!

I think I also noticed two small differences in LibriSpeech:

1. The `dataset_setup.py` currently downloads and processes the `test-other` split of LibriSpeech. As a result, I also have a `test-other.csv` file and `test-other` directory after the setup and consequently more total files. However, I don't think we ever need the `test-other` split in any workload. Removing the files related to `test-other` (almost, see below) resolved the file number and size discrepancy between what I saw and what you reported.
2. The tokenzier `spm_model.vocab` gets written to the temporary data directory instead of the main data directory. I.e. it uses `--temp_dir` instead of `--data_dir`. In here, https://github.com/mlcommons/algorithmic-efficiency/blob/bfa2ba26c658e9d13b79946f165f7c4260b02fbb/datasets/dataset_setup.py#L623, it passes the `extracted_data_dir` (i.e. the `temp_dir`), which is correct, as it is the location of the extracted data files but as a result it also uses this directory when storing the tokenizer.

I think I can fix both in this PR. For 1, I would suggest just not downloading an preprocessing `test-other` and for 2, I will either save the tokenizer correctly in the first place, or move it, depending what is easier to implement.

Another thing I noticed is that you didn't list the `train-other-500` directory in your tree above. But since you did list the `train-other-500.csv` file, and all file numbers and sizes match, I think this is just a copy-paste thing.

**Comment by fsschneider** [comment]
I addressed the points from above with my latest commits.
However, I am still having a slight difference to your reported numbers. I am getting the same total file count at 543323 (via `find -type f | wc -l`) but `du -sch librispeech/` gives me **387G** instead of 388G as you reported.

@priyakasimbeg, could you run `du -sh *` in the `$DATA_DIR/librispeech/` to help me identify where we differ? My output looks like this

```
2,0G	dev-clean
53K	dev-clean.csv
2,0G	dev-other
57K	dev-other.csv
248K	spm_model.vocab
2,0G	test-clean
50K	test-clean.csv
40G	train-clean-100
567K	train-clean-100.csv
143G	train-clean-360
2,1M	train-clean-360.csv
199G	train-other-500
3,1M	train-other-500.csv
```

**Comment by priyakasimbeg** [comment]
Hi Frank, thanks for removing the test-other split and modifying the tokenizer vocab path. 
I see a few differences in the sizes in my directories and files:
```
kasimbeg@kasimbeg-2:~/data/librispeech$ du -sh *
2.0G    dev-clean
56K     dev-clean.csv
2.1G    dev-other
60K     dev-other.csv
248K    spm_model.vocab
2.0G    test-clean
52K     test-clean.csv
40G     train-clean-100
568K    train-clean-100.csv
143G    train-clean-360
2.1M    train-clean-360.csv
200G    train-other-500
3.1M    train-other-500.csv
```
@sourabh2k15 do you know by any chance why the size of some of the splits is different with the current data setup vs when we downloaded and set it up last year?

**Comment by fsschneider** [comment]
I might have to run it again on my end. I am not completely certain that nothing got corrupted during the setup process.

**Comment by fsschneider** [comment]
@priyakasimbeg I believe the problem is/was on my end and some files got corrupted during the processing part.

I think we can merge this PR and I will create a follow up one, should I find any issues with LibriSpeech.

**Pull request merged**
