### PR TITLE
librispeech_deepspeech eager compile

### PR DESCRIPTION
**Pull request by pomonam**
This PR allows librispeech_deepspeech to be torch compilable in the eager backend. 

Note that when we try to use `aot_autograd`, we still get the following error (which is why we are using eager backend and which I am not sure if there is an easy fix):
```
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 1715, in aot_wrapper_dedupe
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 372, in wrapper
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 1328, in aot_dispatch_base
    self.output.compile_subgraph(self, reason=reason)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 541, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/compile_fx.py", line 430, in fw_compiler
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    return inner_compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: compile_fn raised KeyError: torch.complex64
```

cc @chandramouli-sastry

### CODE REVIEW

**Comment by pomonam** [comment]
cc @priyakasimbeg I am running the timing test and will update the results.

**Comment by msaroufim** [comment]
Are you using stable or nightlies? In nightlies this should fall back to eager pytorch so inductor the default backend should work

**Comment by pomonam** [comment]
I was using stable here; I can try with nightlies after the timing experiments. Do you mean in the nightlies, the error encountered during `aot autograd` backend will automatically convert to the eager backend? (Or do you mean this error will be totally fixed)? Thank you!

**Comment by msaroufim** [comment]
So today inductor the default backend doesn't have great complex number support, it's documented here https://github.com/pytorch/pytorch/issues/98161 - there's ways around it by using decompositions into non complex ops and/or falling back to eager

Also aot_eager will give some speedups but I'd really just make sure that the default inductor backend works

**Comment by pomonam** [comment]
Ah, I see! I just finished the timing experiments with this change, and this does seem to bring slight speed improvements. I will try again with nightlies.

**Comment by pomonam** [comment]
I checked that it works on nightlies! I am closing this as I put together a larger PR here: #484.

**Pull request closed without merging**
