### PR TITLE
NCCL Timeout Fix

### LINKED ISSUE #247: WMT torch  NCCL time out error
WMT torch crashes with NCCL time out error. 

## Description
Traceback:
```
I1103 18:06:29.961281 140411023902528 workload.py:130] Translating evaluation dataset.
I1103 18:14:11.759132 140411023902528 submission_runner.py:345] Time since start: 3.33s,        Step: 1,        {'train/accuracy': 0.0007564548963768036, 'train/loss': 10.993585429343776, 'train/bleu': 1.733641314448888e-09, 'validation/accuracy': 0.000908339253065645, 'validation/loss': 11.012303338729025, 'validation/bleu': 1.3789268837869184e-08, 'validation/num_examples': 3000, 'test/accuracy': 0.000986124646155274, 'test/loss': 10.996429648707597, 'test/bleu': 3.041362410039935e-08, 'test/num_examples': 3000}
I1103 18:14:11.763073 140352877815552 logging_writer.py:48] [1] global_step=1, preemption_count=0, test/accuracy=0.000986, test/bleu=0.000000, test/loss=10.996430, test/num_examples=3000, train/accuracy=0.000756, train/bleu=0.000000, train/loss=10.993585, validation/accuracy=0.000908, validation/bleu=0.000000, validation/loss=11.012303, validation/num_examples=3000
[E ProcessGroupNCCL.cpp:737] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605388 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605480 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605492 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605493 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605503 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605508 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605516 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 3603516 milliseconds before timing out.
I1103 19:14:17.344123 140411023902528 checkpoint_utils.py:167] Saved checkpoint to /home/kasimbeg/target_setting/wmt_pytorch/run_3/trial_1/checkpoint
Traceback (most recent call last):
  File "submission_runner.py", line 577, in <module>
    app.run(main)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 561, in main
    FLAGS.tokenizer_vocab_path)
  File "submission_runner.py", line 499, in score_submission_on_workload
    tokenizer_vocab_path)
  File "submission_runner.py", line 304, in train_once
    data_select_rng)
  File "/home/kasimbeg/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/data_selection.py", line 25, in data_selection
    return next(input_queue)
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py", line 271, in _build_input_queue
    dist.broadcast(torch.stack(tensor_list), src=0)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 0.  Original reason for failure was: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 3603516 milliseconds before timing out.
```

## Steps to Reproduce
On kasimbeg-7 run:
```
orchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py \
    --framework=pytorch \
    --data_dir=/home/kasimbeg/tensorflow_datasets \
    --experiment_dir=/home/kasimbeg \
    --experiment_name=target_setting \
    --workload=wmt \
    --submission_path=reference_algorithms/target_setting_algorithms/pytorch_adamw.py \
    --tuning_search_space=reference_algorithms/target_setting_algorithms/wmt/tuning_search_space.json > results_wmt_pytorch_verify.txt 2>&1
```
## Source or Possible Fix
This has happened on other workloads like imagenet as well. Not sure what the root cause is.

### PR DESCRIPTION
**Pull request by pomonam**
This PR should fix #247 resulting from PR #237. As @chandramouli-sastry pointed out, `get_log_dir(..)` function returns `None` for non-rank 0 processes and this results in `dist.barrier()` call in the `checkpoint_utils.py` to hang. 

In light of the change in the way we get `log_dir`, I modified the code accordingly. Especially, I added `dist.barrier()` in front of `time.time()` calls and removed irrelevant `RANK == 0` checks. This should restore the previous behaviour and now imagenet workload does not face NCCL timeout issue.

### CODE REVIEW

**Comment by pomonam** [comment]
Thank you, this should only affect PyTorch workloads and I confirmed that NCCL error gets fixed after this change. I will also run the reference algos.

**Comment by pomonam** [comment]
One minor question: what is the correct way to run the reference algo tests? Previously and now, when I run `reference_algorithm_tests.py`, I get the following error (without removing FLAGS):

```
self = <absl.flags._flagvalues.FlagValues object at 0x7fd00b482bd0>
name = 'all'

    def __getattr__(self, name):
      """Retrieves the 'value' attribute of the flag --name."""
      fl = self._flags()
      if name not in fl:
        raise AttributeError(name)
      if name in self.__dict__['__hiddenflags']:
        raise AttributeError(name)
    
      if self.__dict__['__flags_parsed'] or fl[name].present:
        return fl[name].value
      else:
        error_message = ('Trying to access flag --%s before flags were parsed.' %
                         name)
        if six.PY2:
          # In Python 2, hasattr returns False if getattr raises any exception.
          # That means if someone calls hasattr(FLAGS, 'flag'), it returns False
          # instead of raises UnparsedFlagAccessError even if --flag is already
          # defined. To make the error more visible, the best we can do is to
          # log an error message before raising the exception.
          # Don't log a full stacktrace here since that makes other callers
          # get too much noise.
          logging.error(error_message)
>       raise _exceptions.UnparsedFlagAccessError(error_message)
E       absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --all before flags were parsed.
```

**Comment by znado** [comment]
At HEAD on the main branch, in a new virtual env, I was able to run it with `python tests/reference_algorithm_tests.py --all`. Let me know if that doesn't work!

**Comment by chandramouli-sastry** [comment]
Thank you very much for these fixes -- this should also fix the issue (https://github.com/mlcommons/algorithmic-efficiency/issues/245) with librispeech pytorch workloads; in summary, @sourabh2k15 and I ran the deepspeech workloads by commenting out the checkpointing code as they led to deadlocks but doing so gave rise to a different (randomly occurring) NCCL timeout error as there was no dist.barrier after the logging/checkpointing step.

**Comment by pomonam** [comment]
I see, I was running it incorrectly. It passes the test as expected.

**Comment by runame** [comment]
@znado Can this be merged?

**Pull request merged**
