### PR TITLE
style(librispeech): simplify masking + reshaping

### PR DESCRIPTION
**Pull request by ClashLuke**
It's not a significant change and doesn't impact performance or results. It simply minifies the code by using built-in functions.
If merged, it's probably best to squash the commits, as I've been editing one line at a time via GitHub's Web Editor.

### CODE REVIEW

**Comment by sourabh2k15** [comment]
Hi Luke, did you make any progress on this ? I'm facing a similar issue using flax default LSTM cells and run gets stuck at 75% WER so was curious if you solved the issue

**Comment by ClashLuke** [comment]
Hi Sourabh, thanks for reaching out!\
Unfortunately, I'm still facing the same instabilities as before:
grafik
I've only added the [length-bucketing](https://github.com/ClashLuke/algorithmic-efficiency/commit/c8162a1d8be4255da193eb4451d685a94ff23f01) we discussed and started [padding to multiples of 128](https://github.com/ClashLuke/algorithmic-efficiency/blob/a85e6c48a34bfb09e19a9a56c93e3a5de86bf1af/workloads/librispeech/librispeech_jax/input_pipeline.py#L35-L36) (+21% step/s vs. pad-to-8, +33% step/s vs. pad-to-power-of-2). With these changes, the model now runs 4.2x as fast, but, unfortunately, that's all that happened on my end.\
Do you have any idea what we could change to improve stability?

**Comment by znado** [comment]
@sourabh2k15 do we still need this with the new changes, or can we close it?

**Comment by znado** [comment]
cleaning up old PRs, closing

**Pull request closed without merging**
