### PR TITLE
Feat default dropout in doc

### PR DESCRIPTION
**Pull request by init-22**
Adding default dropout values for each workloads mentioned in this issue: #786

### CODE REVIEW

**Comment by init-22** [comment]
recheck

**Review by priyakasimbeg — APPROVED** [review]

**Comment by priyakasimbeg** [comment]
Hi Isaac, thanks for this PR. Looks great.
Can we remove cifar10 and mnist from the table? Those two are implemented more for testing purposes and aren't part of the 8 AlgoPerf benchmarking workloads.

**Comment by priyakasimbeg** [comment]
Also, can you sign the CLA with the email address you use for your github account so that the CLA check passes. 
If it still does not pass, could you email support@mlcommons.org and ask for help with the CLA check in this PR.

**Comment by morphine00** [comment]
Hi folks, the CLA check is passing. The code needs to be reviewed presumably by @priyakasimbeg (or anyone else in `wg-algorithms`). Note the message after the previous comment, " init-22 dismissed priyakasimbeg’s stale review via 76b084b 2 hours ago".

**Comment by priyakasimbeg** [comment]
Hi Isaac can you run `yapf -i -r -vv -p  scoring/score_submissions.py` to fix the yapf test and push the changes. Typically, we want to make PRs to the dev branch but I think this score_submissions.py file is out of sync with def and has a formatting error that is blocking this PR

**Comment by priyakasimbeg** [comment]
This branch should also be synced with dev, which will fix the yapf tests.

**Comment by init-22** [comment]
recheck

**Review by priyakasimbeg — DISMISSED** [review]

**Pull request merged**
