### PR TITLE
Fix segfault in dataset_setup

### PR DESCRIPTION
**Pull request by msaroufim**
Fixes https://github.com/mlcommons/algorithmic-efficiency/issues/470

Might make your linter mad if you use one but this arrangement worked

## Logs of it working

```
(perf) ubuntu@ip-172-31-41-234:~/algorithmic-efficiency$ python3 datasets/dataset_setup.py   --data_dir=~/data   --wmt
2023-08-10 20:39:37.642657: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/ubuntu/.conda/envs/perf/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
I0810 20:39:38.975371 139772001167168 dataset_setup.py:533] Downloading data to /home/ubuntu/data...
I0810 20:39:38.975744 139772001167168 dataset_setup.py:594] Downloading WMT...
I0810 20:39:38.983139 139772001167168 dataset_info.py:578] Load dataset info from /home/ubuntu/data/wmt14_translate/de-en/1.0.0
I0810 20:39:38.987007 139772001167168 dataset_builder.py:528] Reusing dataset wmt14_translate (/home/ubuntu/data/wmt14_translate/de-en/1.0.0)
I0810 20:39:38.988960 139772001167168 dataset_info.py:578] Load dataset info from /home/ubuntu/data/wmt17_translate/de-en/1.0.0
I0810 20:39:38.991663 139772001167168 dataset_builder.py:528] Reusing dataset wmt17_translate (/home/ubuntu/data/wmt17_translate/de-en/1.0.0)
I0810 20:39:48.913886 139772001167168 logging_logger.py:49] Constructing tf.data.Dataset wmt17_translate for split train, from /home/ubuntu/data/wmt17_translate/de-en/1.0.0
I0810 20:39:48.957852 139772001167168 tokenizer.py:122] Building SentencePiece vocab from data.
sentencepiece_trainer.cc(177) LOG(INFO) Running command: --input=/tmp/ds_charsclp52xmk --vocab_size=32000 --character_coverage=1.0 --model_prefix=/tmp/sp_tmpdpx511ws --model_type=unigram
sentencepiece_trainer.cc(77) LOG(INFO) Starts training with : 
trainer_spec {
  input: /tmp/ds_charsclp52xmk
  input_format: 
  model_prefix: /tmp/sp_tmpdpx511ws
  model_type: UNIGRAM
  vocab_size: 32000
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter: 
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars: 
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇ 
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv: 
}
denormalizer_spec {}
trainer_interface.cc(351) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(183) LOG(INFO) Loading corpus: /tmp/ds_charsclp52xmk
trainer_interface.cc(407) LOG(INFO) Loaded all 70526 sentences
trainer_interface.cc(423) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(423) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(423) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(428) LOG(INFO) Normalizing sentences...
trainer_interface.cc(537) LOG(INFO) all chars count=9897150
trainer_interface.cc(558) LOG(INFO) Alphabet size=432
trainer_interface.cc(559) LOG(INFO) Final character coverage=1
trainer_interface.cc(591) LOG(INFO) Done! preprocessed 70526 sentences.
unigram_model_trainer.cc(222) LOG(INFO) Making suffix array...
unigram_model_trainer.cc(226) LOG(INFO) Extracting frequent sub strings... node_num=4956538
unigram_model_trainer.cc(274) LOG(INFO) Initialized 322599 seed sentencepieces
trainer_interface.cc(597) LOG(INFO) Tokenizing input sentences with whitespace: 70526
trainer_interface.cc(608) LOG(INFO) Done! 169388
unigram_model_trainer.cc(564) LOG(INFO) Using 169388 sentences for EM training
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=97103 obj=12.603 num_tokens=356934 num_tokens/piece=3.67583
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=84113 obj=10.1342 num_tokens=358856 num_tokens/piece=4.26636
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=63037 obj=10.1593 num_tokens=379805 num_tokens/piece=6.02511
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=62964 obj=10.1277 num_tokens=379928 num_tokens/piece=6.03405
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=47216 obj=10.2858 num_tokens=410631 num_tokens/piece=8.69686
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=47208 obj=10.2475 num_tokens=410629 num_tokens/piece=8.69829
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=35406 obj=10.4605 num_tokens=445998 num_tokens/piece=12.5967
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=35405 obj=10.4166 num_tokens=446301 num_tokens/piece=12.6056
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=35200 obj=10.4197 num_tokens=446904 num_tokens/piece=12.6961
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=35200 obj=10.4186 num_tokens=446903 num_tokens/piece=12.6961
trainer_interface.cc(686) LOG(INFO) Saving model: /tmp/sp_tmpdpx511ws.model
trainer_interface.cc(698) LOG(INFO) Saving vocabs: /tmp/sp_tmpdpx511ws.vocab
I0810 20:40:10.207773 139772001167168 xla_bridge.py:622] Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0810 20:40:10.208014 139772001167168 xla_bridge.py:622] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0810 20:40:10.208805 139772001167168 xla_bridge.py:622] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
W0810 20:40:10.208985 139772001167168 xla_bridge.py:636] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
I0810 20:40:10.210575 139772001167168 tokenizer.py:96] copied /tmp/sp_tmpdpx511ws.model to /home/ubuntu/data/wmt_sentencepiece_model
(perf) ubuntu@ip-172-31-41-234:~/algorithmic-efficiency$ 
```

### CODE REVIEW

**Comment by msaroufim** [comment]
recheck

**Comment by msaroufim** [comment]
recheck

**Comment by sourabh2k15** [comment]
Can you try simply removing the tf import and the associated usage : `tf.config.set_visible_devices([], 'GPU')` 

I didn't get segfaults after doing that so was gonna send a PR , since you have the setup working just try it out and let us know here

**Comment by sourabh2k15** [comment]
you might also need the change in https://github.com/mlcommons/algorithmic-efficiency/pull/478 for ffmpeg install in case you want to use the docker image 

happy to delete my PR if tf import removal doesn't work in your setup

**Comment by msaroufim** [comment]
Still segfaults for me unfortunately https://gist.github.com/msaroufim/8fa498d1986f8b748a5fd2847168dc3f

**Comment by msaroufim** [comment]
recheck

**Comment by sourabh2k15** [comment]
and just to confirm this happens with librispeech as well after https://github.com/mlcommons/algorithmic-efficiency/pull/478 ? I'm using our docker image as it's easiest to reproduce

Can you try this : 

```
git clone https://github.com/mlcommons/algorithmic-efficiency.git
cd algorithmic-efficiency

cd docker 
docker build -t mlcommons:local --build-arg framework=pytorch .

# run docker image , this assumes the following base directories: data, experiment_runs and a git clone of algorithmic-efficiency

docker run -t -d -v $HOME/data/:/data/ -v $HOME/experiment_runs/:/experiment_runs -v $HOME/algorithmic-efficiency/:/code --gpus all --ipc=host mlcommons:local -b true

# get docker container id 
docker ps

# bash into container
docker exec -it <container_id> /bin/bash

# run dataset setup 
cd code 
python3 datasets/dataset_setup.py   --data_dir=./data  --librispeech

```

**Comment by sourabh2k15** [comment]
if the import reordering changes in this PR resolve segfault in your setup we can also accept that, I'll verify that it doesn't break something else in docker setup

**Comment by msaroufim** [comment]
I'll be in meetings for the next 2h but I still think the workflow should work for both docker and no docker. Regardless building your dockerfile now

**Comment by msaroufim** [comment]
The dockerscript is just hanging for me 

(perf) ubuntu@ip-172-31-41-234:~/algorithmic-efficiency/datasets$ docker exec -it b82cb5b7c8ca /bin/bash
root@b82cb5b7c8ca:/# cd code 
root@b82cb5b7c8ca:/code# python3 datasets/dataset_setup.py   --data_dir=./data  --librispeech
2023-08-10 22:30:30.873048: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-10 22:30:31.850078: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Anecdotally my colleageus also ran into this very same issue, only way around it was installing torch nightlies

**Comment by msaroufim** [comment]
recheck

**Comment by priyakasimbeg** [comment]
@msaroufim if I understand correctly:
1. librispeech dataset up fails with segfault when running data_setup.py --librispeech directly on your vm.
2. the data_setup.py command hangs when run inside a docker container.
3. upgrading to pytorch-nightly resolves the hanging issue inside the docker container?

**Comment by msaroufim** [comment]
> * the data_setup.py command hangs when run inside a docker container.

Yes exactly

**Comment by priyakasimbeg** [comment]
Are the segfaults still occurring with your import order changes?

**Comment by msaroufim** [comment]
line 599   is `app.run(main)`

With my import order changes I don' see a segfault anymore

```
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv: 
}
denormalizer_spec {}
trainer_interface.cc(351) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(183) LOG(INFO) Loading corpus: /tmp/ds_charsjfyulflx
trainer_interface.cc(407) LOG(INFO) Loaded all 70526 sentences
trainer_interface.cc(423) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(423) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(423) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(428) LOG(INFO) Normalizing sentences...
trainer_interface.cc(537) LOG(INFO) all chars count=9897150
trainer_interface.cc(558) LOG(INFO) Alphabet size=432
trainer_interface.cc(559) LOG(INFO) Final character coverage=1
trainer_interface.cc(591) LOG(INFO) Done! preprocessed 70526 sentences.
unigram_model_trainer.cc(222) LOG(INFO) Making suffix array...
unigram_model_trainer.cc(226) LOG(INFO) Extracting frequent sub strings... node_num=4956538
unigram_model_trainer.cc(274) LOG(INFO) Initialized 322599 seed sentencepieces
trainer_interface.cc(597) LOG(INFO) Tokenizing input sentences with whitespace: 70526
trainer_interface.cc(608) LOG(INFO) Done! 169388
unigram_model_trainer.cc(564) LOG(INFO) Using 169388 sentences for EM training
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=97103 obj=12.603 num_tokens=356934 num_tokens/piece=3.67583
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=84113 obj=10.1342 num_tokens=358856 num_tokens/piece=4.26636
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=63037 obj=10.1593 num_tokens=379805 num_tokens/piece=6.02511
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=62964 obj=10.1277 num_tokens=379928 num_tokens/piece=6.03405
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=47216 obj=10.2858 num_tokens=410631 num_tokens/piece=8.69686
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=47208 obj=10.2475 num_tokens=410629 num_tokens/piece=8.69829
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=35406 obj=10.4605 num_tokens=445998 num_tokens/piece=12.5967
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=35405 obj=10.4166 num_tokens=446301 num_tokens/piece=12.6056
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=0 size=35200 obj=10.4197 num_tokens=446904 num_tokens/piece=12.6961
unigram_model_trainer.cc(580) LOG(INFO) EM sub_iter=1 size=35200 obj=10.4186 num_tokens=446903 num_tokens/piece=12.6961
trainer_interface.cc(686) LOG(INFO) Saving model: /tmp/sp_tmpc34ughnw.model
trainer_interface.cc(698) LOG(INFO) Saving vocabs: /tmp/sp_tmpc34ughnw.vocab
I0810 23:41:11.586649 140573992568640 xla_bridge.py:455] Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0810 23:41:11.586850 140573992568640 xla_bridge.py:455] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0810 23:41:11.587725 140573992568640 xla_bridge.py:455] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
I0810 23:41:11.587898 140573992568640 xla_bridge.py:455] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
W0810 23:41:11.588049 140573992568640 xla_bridge.py:463] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
I0810 23:41:11.589121 140573992568640 tokenizer.py:96] copied /tmp/sp_tmpc34ughnw.model to /code/data/wmt_sentencepiece_model
root@b82cb5b7c8ca:/code# 
```

**Comment by priyakasimbeg** [comment]
Can you share the specs of your machine (RAM, disk, GPUs). I'll try to reproduce it on a similar VM because it seems like we haven't been able to reproduce the segfault after removing the tensorflow import in Sourabh's earlier PR.

**Comment by priyakasimbeg** [comment]
Also thanks for working on fixing this. If this PR is the only solution we come up with we should probably merge it but there may be another issue underneath the surface that we're not addressing at the moment with this fix

**Comment by msaroufim** [comment]
I hear you it is kinda ugly but it's a known problem with sentencepiece, see this for example https://github.com/Lightning-AI/lightning/issues/11663#issuecomment-1065375768

Regardless here's some of my machine info. 

```
(perf) ubuntu@ip-172-31-41-234:~$ wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
--2023-08-10 23:58:52--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21653 (21K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py           100%[==================================>]  21.15K  --.-KB/s    in 0.001s  

2023-08-10 23:58:53 (13.9 MB/s) - ‘collect_env.py’ saved [21653/21653]

(perf) ubuntu@ip-172-31-41-234:~$ python collect_env.py 
Collecting environment information...
PyTorch version: 2.1.0.dev20230810+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.1
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1015-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 510.73.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:                        1
CPU MHz:                         2699.961
CPU max MHz:                     3000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4600.00
Hypervisor vendor:               Xen
Virtualization type:             full
L1d cache:                       512 KiB
L1i cache:                       512 KiB
L2 cache:                        4 MiB
L3 cache:                        45 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230810+cu118
[pip3] torchvision==0.16.0.dev20230810+cu118
[pip3] triton==2.0.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.1.0.dev20230810+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230810+cu118          pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
```

**Comment by priyakasimbeg** [comment]
Just noticed that there was still the tf import in this data_setup.py. Did you try running with the old import order without importing tf by any chance?

**Comment by msaroufim** [comment]
Adding it or removing tf setup had no impact for me on the segfault

**Review by priyakasimbeg — APPROVED** [review]
LGTM on this changed import order.
Thanks for getting this fix in!

**Comment by msaroufim** [comment]
CI looks green, anything left before we can merge this?

**Pull request merged**
